# cargo-about: the full license text of every crate linked into playerui and
# player-guard-helper, generated for each release (.github/workflows/release.yml)
accepted = ["MIT", "Apache-2.0", "Unlicense", "Unicode-3.0"]
